export const queryKeys = {
  snapshot: ["snapshot"] as const,
  ideas: ["ideas"] as const,
  idea: (slug: string) => ["idea", slug] as const,
  ideaContent: (slug: string) => ["idea-content", slug] as const,
  ideaStudies: (slug: string) => ["idea-studies", slug] as const,
  ideaSources: (slug: string) => ["idea-sources", slug] as const,
  ideaChildren: (slug: string) => ["idea-children", slug] as const,
  ideaInitialExpectation: (slug: string) => ["idea-initial-expectation", slug] as const,
  ideaThreads: (slug: string) => ["idea-threads", slug] as const,
  studyAnnotations: (slug: string, studyNumber: number) => ["study-annotations", slug, studyNumber] as const,
  studyCounts: ["study-counts"] as const,
  proposals: ["proposals"] as const,
  proposal: (slug: string) => ["proposal", slug] as const,
  proposalContent: (slug: string) => ["proposal-content", slug] as const,
  threads: ["threads"] as const,
  thread: (id: number) => ["thread", id] as const,
  workers: ["workers"] as const,
  worker: (id: number) => ["worker", id] as const,
  workerRuns: (date: string) => ["worker-runs", date] as const,
  workerHistory: (workerId: number, filename: string) => ["worker-history", workerId, filename] as const,
  settings: ["settings"] as const,
  providerDefaults: ["provider-defaults"] as const,
  responders: ["responders"] as const,
  search: (query: string) => ["search", query] as const,
};
